#pragma kernel CSMain

float2 Direction;
RWBuffer<float3> Positions;

float SampleFunction(float2 dir, float2 position)
{
    return sin(4 * dir.x * position.x) + sin(4 * dir.y * position.y);
}

[numthreads(8, 8, 1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    const uint idx = id.x * 128 + id.y;
    float3 prevPos = Positions[idx];
    Positions[idx] = float3(prevPos.x, sin(4 * id.x / 128.0f), prevPos.z);
}