#pragma kernel CSMain

float Time;
float2 Direction;
RWStructuredBuffer<float4> Positions;

float SampleFunction(float2 dir, float2 position)
{
    position += Time;
    return 0.1 * (sin(4 * dir.x * position.x) + sin(4 * dir.y * position.y));
}

[numthreads(8, 8, 1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    const uint idx = id.x * 128 + id.y;
    Positions[idx] = float4(Positions[idx].x, SampleFunction(Direction, float2(id.x / 128.0f, id.y / 128.0f)), Positions[idx].z, 0);
}